# data path
data_type: "single"
data_root: "/data/users/ys221/data/DFEW/data_affine/single_label/"
work_dir: "./output/DFEW"
fold_idx: 1

# speed: GPU and memory
gpu_id: 7
num_workers: 4
Flag_mGPU_blocks: False
List_mGPU_blocks: [0, 1]

# hyper-parameter
batch_size: 32
test_gap: "epoch"
optimizer: "Adam"
lr_init: 1e-3

# preprocess: data augment
train_data_augment: False
size_Resize_te: 112

# model: model info, training strategy
model_name: "r3d_18"
model_pretrain: False
model_init: True